server:
#  port: 8001
  port: ${PORT:0}

spring:
  application:    name: caderneta-contas
  zipkin:
    base-url: http://localhost:9411/
  cache:
    type: redis
  redis:
    host: ${REDISCLOUD_URL:localhost}
    port: ${PORT_REDIS:6379}
    password: ${REDIS_PASS:''}
    
      
eureka:
  client:
    service-url:
      #defaultZone: http://caderneta-eureka-server:8761/eureka #Esta url aponta para o container docker
      defaultZone: ${URL_EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

feign:
    hystrix:
        enabled: true