CREATE TABLE IF NOT EXISTS TB_STATUS_CONTA
(
    ID serial NOT NULL,
    DESCRICAO VARCHAR(255),
    
    CONSTRAINT pk_status_conta primary key (ID)
);

CREATE TABLE IF NOT EXISTS TB_TIPO_CONTA
(
    ID serial NOT NULL,
    NOME_TIPO_CONTA VARCHAR(255),
    DESC_TIPO_CONTA VARCHAR(255),
    
    CONSTRAINT pk_tipo_conta primary key (ID)
);

CREATE TABLE IF NOT EXISTS TB_MES
(
    ID serial NOT NULL,
    DESC_MES VARCHAR (255) NOT NULL,
     
    CONSTRAINT pk_mes primary key (ID)
);

CREATE TABLE IF NOT EXISTS TB_CONTA
(
    ID serial NOT NULL,
    VALOR_CONTA DECIMAL (10,2) NOT NULL,
    DT_VENCIMENTO DATE NOT NULL,
    DT_PAGAMENTO DATE,    
    QTD_PARCELAS BIGINT,
    COMENTARIO VARCHAR(500),
    ID_MES BIGINT NOT NULL,
    ID_STATUS_CONTA BIGINT NOT NULL,
    ID_TIPO_CONTA BIGINT NOT NULL,    
    ID_USUARIO BIGINT NOT NULL,
    DT_CADASTRO DATE DEFAULT NOW(),

	CONSTRAINT pk_conta primary key (ID),
	FOREIGN KEY (ID_MES) REFERENCES TB_MES(ID),
    FOREIGN KEY (ID_STATUS_CONTA) REFERENCES TB_STATUS_CONTA(ID),
    FOREIGN KEY (ID_TIPO_CONTA) REFERENCES TB_TIPO_CONTA(ID)
);