-- ADICIONANDO OS TIPOS DE CONTAS
INSERT INTO TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('ALUGUEL', 'ALUGUEL');
INSERT INTO TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('AGUA', 'ÁGUA');
INSERT INTO TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('LUZ', 'ENERGIA');
INSERT INTO TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('GAS', 'GÁS');
INSERT INTO TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('COMBO', 'TV + INTERNET E/OU TELEFONE FIXO');
INSERT INTO TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('CC', 'CARTÃO DE CREDITO');
INSERT INTO TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('CELULAR', 'CELULAR');
INSERT INTO TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('FINANCIAMANTO IMOBILIARIO', 'FINANCIAMANTO IMOBILIARIO');
INSERT INTO TB_TIPO_CONTA (NOME_TIPO_CONTA, DESC_TIPO_CONTA) VALUES ('FINANCIAMANTO AUTOMOTIVO', 'FINANCIAMANTO AUTOMOTIVO');

-- ADICIONANDO O STATUS DA CONTA
INSERT INTO TB_STATUS_CONTA(DESCRICAO) VALUES ('A PARGAR');
INSERT INTO TB_STATUS_CONTA(DESCRICAO) VALUES ('PAGO');
INSERT INTO TB_STATUS_CONTA(DESCRICAO) VALUES ('VENCIDO');
INSERT INTO TB_STATUS_CONTA(DESCRICAO) VALUES ('PARCELADO');

-- ADICIONANDO OS MESES
INSERT INTO TB_MES(DESC_MES) VALUES ('JANEIRO');
INSERT INTO TB_MES(DESC_MES) VALUES ('FEVEREIRO');
INSERT INTO TB_MES(DESC_MES) VALUES ('MARÇO');
INSERT INTO TB_MES(DESC_MES) VALUES ('ABRIL');
INSERT INTO TB_MES(DESC_MES) VALUES ('MAIO');
INSERT INTO TB_MES(DESC_MES) VALUES ('JUNHO');
INSERT INTO TB_MES(DESC_MES) VALUES ('JULHO');
INSERT INTO TB_MES(DESC_MES) VALUES ('AGOSTO');
INSERT INTO TB_MES(DESC_MES) VALUES ('SETEMBRO');
INSERT INTO TB_MES(DESC_MES) VALUES ('OUTUBRO');
INSERT INTO TB_MES(DESC_MES) VALUES ('NOVEMBRO');
INSERT INTO TB_MES(DESC_MES) VALUES ('DEZEMBRO');